DROP TABLE PAIS
DROP TABLE ESTADO 
DROP TABLE CIDADE
DROP TABLE BAIRRO
DROP TABLE ENDERECO_CLIENTE 

CREATE TABLE PAIS (
ID_PAIS NUMBER GENERATED ALWAYS AS IDENTITY,
NOME_PAIS VARCHAR2 (30) NOT NULL,
PRIMARY KEY (ID_PAIS)
);

CREATE TABLE ESTADO (
ID_ESTADO NUMBER GENERATED ALWAYS AS IDENTITY,
NOME_ESTADO VARCHAR2 (30) NOT NULL,
ID_PAIS NUMBER,
PRIMARY KEY (ID_ESTADO)
);

ALTER TABLE ESTADO ADD CONSTRAINT FK_ESTADO FOREIGN KEY (ID_PAIS) REFERENCES PAIS;

CREATE TABLE CIDADE (
ID_CIDADE NUMBER GENERATED ALWAYS AS IDENTITY,
NOME_CIDADE VARCHAR2 (30) NOT NULL,
ID_ESTADO NUMBER,
PRIMARY KEY (ID_CIDADE)
);

ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO;

CREATE TABLE BAIRRO (
ID_BAIRRO NUMBER GENERATED ALWAYS AS IDENTITY,
NOME_BAIRRO VARCHAR2 (30) NOT NULL,
ID_CIDADE NUMBER,
PRIMARY KEY (ID_BAIRRO)
);

ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE;

CREATE TABLE ENDERECO_CLIENTE(
ID_ENDERECO_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY,
CEP VARCHAR2 (30),
ID_BAIRRO NUMBER,
PONTO_REFERENCIA VARCHAR2 (30),
PRIMARY KEY (ID_ENDERECO_CLIENTE)
);

ALTER TABLE ENDERECO_CLIENTE ADD CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO;

